%%  ------------------- INITIALISATION CELL (RUN THIS BEFORE ANY ANALYSES)  ----------------------

% This cell loads all the subject data and populates the containers
% required for subsequent analysis. All common quantities are calculated in
% this cell.

% Note - we don't have Jennifer Day4 S1 trainFeedback


clear 
disp('Clearing Workspace!')
clc
fileDir = '~/Box Sync/AuditoryTaskV9/RawData/';

storeFileDir = '~/Dropbox/AuditoryTask/AuditoryTaskV9/Data/';
storeFile = [storeFileDir 'train_likeWidth(' datestr(now) ')'];

% Calculating the training likelihood width using *all* the sessions
% including DAY1. BUT, I'm discarding the 1st block on each day
% This makes more sense given that the subjects take ~5-6 trials to get
% used to the virtual space and the reporting procedure.

subjectList = {...
    'AbhinavD1S1trainFeedback(15-Jul-2014).mat',...
    'AbhinavD2S1trainFeedback(18-Jul-2014).mat',...
    'AbhinavD3S1trainFeedback(23-Jul-2014).mat',...
    'AbhinavD4S1trainFeedback(24-Jul-2014).mat',...
    'AbhinavD5S1trainFeedback(25-Jul-2014).mat',...
    'AbhinavD6S1trainFeedback(29-Jul-2014).mat',...
    'AmiraD4S1trainFeedback(09-Jul-2014).mat',...
    'AmiraD5S1trainFeedback(21-Jul-2014).mat',...
    'AmiraD6S1trainFeedback(22-Jul-2014).mat',...
    'AmiraD7S1trainFeedback(25-Jul-2014).mat',...
    'AmiraD8S1trainFeedback(28-Jul-2014).mat',...
    'ArchanaD2S1trainFeedback(09-Jul-2014).mat',...
    'ArchanaD3S1trainFeedback(10-Jul-2014).mat',...
    'ArchanaD4S1trainFeedback(21-Jul-2014).mat',...
    'ArchanaD5S1trainFeedback(22-Jul-2014).mat',...
    'ArchanaD6S1trainFeedback(28-Jul-2014).mat',...
    'AyobamiD4S1trainFeedback(09-Jul-2014).mat',...
    'AyobamiD5S1trainFeedback(10-Jul-2014).mat',...
    'AyobamiD6S1trainFeedback(11-Jul-2014).mat',...
    'AyobamiD7S1trainFeedback(23-Jul-2014).mat',...
    'AyobamiD8S1trainFeedback(24-Jul-2014).mat',...
    'ChristinaD1S1trainFeedback(29-Jul-2014).mat',...
    'ChristinaD2S1trainFeedback(30-Jul-2014).mat',...
    'ChristinaD3S1trainFeedback(31-Jul-2014).mat',...
    'DawnD1S1trainFeedback(31-Jul-2014).mat',...
    'DawnD2S1trainFeedback(04-Aug-2014).mat',...
    'DawnD3S1trainFeedback(05-Aug-2014).mat',...
    'DawnD4S1trainFeedback(06-Aug-2014).mat',...
    'DawnD5S1trainFeedback(08-Aug-2014).mat',...
    'DhruvaD1S1trainFeedback(16-Jul-2014)',...
    'DhruvaD2S1trainFeedback(17-Jul-2014).mat',...
    'DhruvaD3S1trainFeedback(21-Jul-2014).mat',...
    'HaftomD2S1trainFeedback(16-Jul-2014).mat',...
    'HaftomD3S1trainFeedback(17-Jul-2014).mat',...
    'HaftomD4S1trainFeedback(23-Jul-2014).mat',...
    'HaftomD5S1trainFeedback(25-Jul-2014).mat',...
    'HaftomD6S1trainFeedback(28-Jul-2014).mat',...
    'JenniferD1S1trainFeedback(30-Jul-2014).mat',...
    'JenniferD2S1trainFeedback(01-Aug-2014).mat',...
    'JenniferD3S1trainFeedback(02-Aug-2014).mat',...
    'JessicaD1S1trainFeedback(28-Jul-2014).mat',...
    'JessicaD2S1trainFeedback(29-Jul-2014).mat',...
    'JessicaD3S1trainFeedback(03-Aug-2014).mat',...
    'JessicaD4S1trainFeedback(04-Aug-2014).mat',...
    'JulieD1S1trainFeedback(15-Jul-2014).mat',...
    'JulieD2S1trainFeedback(17-Jul-2014).mat',...
    'JulieD3S1trainFeedback(18-Jul-2014).mat',...
    'JustynD1S1trainFeedback(24-Jul-2014).mat',...
    'JustynD2S1trainFeedback(25-Jul-2014).mat',...
    'JustynD3S1trainFeedback(28-Jul-2014).mat',...
    'JustynD4S1trainFeedback(29-Jul-2014).mat',...
    'KatelynD1S1trainFeedback(09-Jul-2014).mat',...
    'KatelynD2S1trainFeedback(10-Jul-2014).mat',...
    'KatelynD3S1trainFeedback(11-Jul-2014).mat',...
    'KatelynD4S1trainFeedback(16-Jul-2014).mat',...
    'KatelynD5S1trainFeedback(17-Jul-2014).mat',...
    'KatelynD6S1trainFeedback(19-Jul-2014).mat',...
    'KelseyD6S1trainFeedback(09-Jul-2014).mat',...
    'KelseyD7S1trainFeedback(10-Jul-2014).mat',...
    'KelseyD8S1trainFeedback(17-Jul-2014).mat',...
    'KelseyD9S1trainFeedback(04-Aug-2014).mat',...
    'KenyaD1S1trainFeedback(31-Jul-2014).mat',...
    'KenyaD2S1trainFeedback(01-Aug-2014).mat',...
    'KenyaD3S1trainFeedback(03-Aug-2014).mat',...
    'KenyaD4S1trainFeedback(05-Aug-2014).mat',...
    'KenyaD5S1trainFeedback(07-Aug-2014).mat',...
    'KenyaD6S1trainFeedback(08-Aug-2014).mat',...
    'MarinaD1S1trainFeedback(24-Jul-2014).mat',...
    'MarinaD2S1trainFeedback(01-Aug-2014).mat',...
    'MarinaD3S1trainFeedback(02-Aug-2014).mat',...
    'MarinaD4S1trainFeedback(03-Aug-2014).mat',...
    'MarinaD5S1trainFeedback(05-Aug-2014).mat',...
    'MarinaD6S1trainFeedback(08-Aug-2014).mat',...
    'RafaelD1S1trainFeedback(30-Jul-2014).mat',...
    'RafaelD2S1trainFeedback(31-Jul-2014).mat',...
    'RafaelD3S1trainFeedback(01-Aug-2014).mat',...
    'RafaelD4S1trainFeedback(04-Aug-2014).mat',...
    'RafaelD5S1trainFeedback(05-Aug-2014).mat',...
    'RobD1S1trainFeedback(21-Jul-2014).mat',...
    'RobD2S1trainFeedback(23-Jul-2014).mat',...
    'RobD3S1trainFeedback(24-Jul-2014).mat',...
    'SharonD1S1trainFeedback(30-Jul-2014).mat',...
    'SharonD2S1trainFeedback(31-Jul-2014).mat',...
    'SharonD3S1trainFeedback(01-Aug-2014).mat',...
    'SharonD4S1trainFeedback(02-Aug-2014).mat',...
    'SharonD5S1trainFeedback(03-Aug-2014).mat',...
    'SharonD6S1trainFeedback(04-Aug-2014).mat',...
    'ValerieD2S1trainFeedback(09-Jul-2014).mat',...
    'ValerieD3S1trainFeedback(10-Jul-2014).mat',...
    'ValerieD4S1trainFeedback(15-Jul-2014).mat',...
    'ValerieD5S1trainFeedback(16-Jul-2014).mat',...
    'ValerieD6S1trainFeedback(18-Jul-2014).mat',...
    };



% New data collection
subjectList = {subjectList{:},...
         'CarolineD1S1trainFeedback(28-Apr-2016).mat',...
         'CarolineD2S1trainFeedback(03-May-2016).mat',...
         'CarolineD3S1trainFeedback(04-May-2016).mat',...
         'CarolineD4S1trainFeedback(06-May-2016).mat',...
         'DiarraD1S1trainFeedback(04-May-2016).mat',...
         'DiarraD2S1trainFeedback(05-May-2016).mat',...
         'DiarraD3S1trainFeedback(06-May-2016).mat',...
         'DiarraD4S1trainFeedback(09-May-2016).mat',...
         'HarrisonD1S1trainFeedback(20-Apr-2016).mat',...
         'HarrisonD2S1trainFeedback(21-Apr-2016).mat',...
         'HarrisonD3S1trainFeedback(26-Apr-2016).mat',...
         'HarrisonD4S1trainFeedback(03-May-2016).mat',...
         'MACD1S1trainFeedback(10-May-2016).mat',...
         'MACD2S1trainFeedback(12-May-2016).mat',...
         'MACD3S1trainFeedback(13-May-2016).mat',...
         'MACD4S1trainFeedback(14-May-2016).mat',...
         'MauriceD1S1trainFeedback(18-Apr-2016).mat',...
         'MauriceD2S1trainFeedback(19-Apr-2016).mat',...
         'MauriceD3S1trainFeedback(20-Apr-2016).mat',...
         'MauriceD4S1trainFeedback(22-Apr-2016).mat',...
         'MBD1S1trainFeedback(11-May-2016).mat',...
         'MBD2S1trainFeedback(12-May-2016).mat',...
         'MBD3S1trainFeedback(13-May-2016).mat',...
         'MBD4S1trainFeedback(14-May-2016).mat',...
         'MKD1S1trainFeedback(10-May-2016).mat',...
         'MKD2S1trainFeedback(11-May-2016).mat',...
         'MKD3S1trainFeedback(16-May-2016).mat',...
         'MKD4S1trainFeedback(17-May-2016).mat',...
         'SylviaD1S1trainFeedback(28-Apr-2016).mat',...
         'SylviaD2S1trainFeedback(03-May-2016).mat',...
         'SylviaD3S1trainFeedback(05-May-2016).mat',...
         'SylviaD4S1trainFeedback(06-May-2016).mat',...
         'ZBD1S1trainFeedback(12-May-2016).mat',...
         'ZBD2S1trainFeedback(13-May-2016).mat',...
         'ZBD3S1trainFeedback(16-May-2016).mat',...
         'ZBD4S1trainFeedback(17-May-2016).mat',...
               };

%ID = 1:length(subjectList);
ID = [1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 ...
    6 6 6 6 6 7 7 7 8 8 8 8 8 9 9 9 10 10 10 10 11 11 11 12 12 12 12,...
    13 13 13 13 13 13 14 14 14 14 15 15 15 15 15 15 16 16 16 16 16 16,...
    17 17 17 17 17 18 18 18 19 19 19 19 19 19 20 20 20 20 20 21 21 21 21,...
    22 22 22 22 23 23 23 23 24 24 24 24 25 25 25 25 26 26 26 26 27 27 27 27 ...
    28 28 28 28 29 29 29 29];


uniqueID = unique(ID);
uniqueStds = [10 20];

% OK, so here's how to do the analysis on a subset of subjects:
% If you want to do the analsysi on, say, subjects  1, 4  and 5, then set ifReject to
% false and set includeID = [ 1 4 5].
% If you want to do the analysis on all subjects other than 1 4 & 5, the
% set ifReject to true, and set excludeID = [1 4 5]

ifReject = false;
includeID = uniqueID;
%includeID =  [10:20];%[14 15 18 19 20]; %10 11 12 13
%includeID = [1];

%excludeID = [17 16 14 3 7];

if(ifReject)
    for i1 = 1:length(excludeID)
        subjectList(ID == excludeID(i1)) = [];
        ID(ID == excludeID(i1)) = [];
    end
    
else
    for i1 = 1:length(uniqueID)
        if(~any(includeID == uniqueID(i1)))
            subjectList(ID == uniqueID(i1)) = [];
            ID(ID == uniqueID(i1)) = [];
        end
    end
    
end

if(length(ID) ~= length(subjectList))
    error('Enter the correct ID list');
end
subjectCount = zeros(length(uniqueID),1);



outcomeAngles = 0:15:180;
train_PE_session = nan(length(subjectList),1);
train_PE_angle_session = nan(length(subjectList),length(outcomeAngles));
train_PE_subject = nan(length(unique(ID)),1);
train_PE_angle_subject = nan(length(unique(ID)),length(outcomeAngles));

train_PE_subject_3_spatial_zones = nan(length(unique(ID)),3); % column 1 is 0-30 & 150-180 etc


training_all_percpErr = [];
training_all_outcome = [];
training_all_estimate = [];
training_all_ID = [];


% ***************** DISCARD THE FIRST BLOCK ********
train_sel_idx = 14:78;

for i1 = 1:length(subjectList)
    
    fprintf('Processing subject ---> %d\n',i1);
    
    aux = load([fileDir subjectList{i1}]);
    data = aux.data;
    
    idx3 = strcmp({data.group},'isFixedTrial');
    isFixed = {data(idx3).item}';
    isFixed = cell2mat(isFixed);
    
    idx1 = strcmp({data.group},'outcome');
    outcomes = {data(idx1).item}';
    outcomes = cell2mat(outcomes);
    outcomes = outcomes(isFixed);
    
    if(length(outcomes) ~= 78)
        error('Training outcomes looks fishy!!')
    end
    
    %use blocks 2-6
    outcomes = outcomes(train_sel_idx);
    
    
    idx2 = strcmp({data.group},'percept');
    estimate = {data(idx2).item}';
    estimate = cell2mat(estimate);
    estimate = estimate*180/pi;
    
    if(length(estimate) ~= 78)
        error('Training outcomes looks fishy!!')
    end
    estimate = estimate(train_sel_idx);
    
    
    auxErr = abs(outcomes - estimate);
    percpErr = outcomes - estimate;
    %percpErr(auxErr > 40) = nan;
    
    train_PE_session(i1) = nanstd(percpErr);
    for i2 = 1:length(outcomeAngles)
       auxAngleErr = percpErr(outcomes == outcomeAngles(i2));
       train_PE_angle_session(i1,i2) = nanstd(auxAngleErr);
        
    end
    
    training_all_estimate = [training_all_estimate; estimate];
    training_all_percpErr = [training_all_percpErr; percpErr];
    training_all_outcome = [training_all_outcome; outcomes];
    training_all_ID = [training_all_ID; ID(i1)*ones(length(outcomes),1)];
    
    
end


for i1 = 1:length(unique(ID))
    
    selSubj = training_all_ID == i1;
    auxPercpErr= training_all_percpErr(selSubj);
    auxOutcome = training_all_outcome(selSubj);
    
    train_PE_subject(i1) = nanstd(auxPercpErr);
    for i2 = 1:length(outcomeAngles)
       auxAngleErr = auxPercpErr(auxOutcome == outcomeAngles(i2));
       train_PE_angle_subject(i1,i2) = nanstd(auxAngleErr);
        
    end
    
    spatial_idx1 = (auxOutcome >= 0 & auxOutcome <= 30) | ...
                        (auxOutcome >= 150 & auxOutcome <= 180);
                    
    spatial_idx2 = (auxOutcome >= 30 & auxOutcome <= 60) | ...
                        (auxOutcome >= 120 & auxOutcome <= 150);
                    
                    
    spatial_idx3 = (auxOutcome >= 60 & auxOutcome <= 120);
    
    
    train_PE_subject_3_spatial_zones(i1,1) = nanstd(auxPercpErr(spatial_idx1));
    train_PE_subject_3_spatial_zones(i1,2) = nanstd(auxPercpErr(spatial_idx2));
    train_PE_subject_3_spatial_zones(i1,3) = nanstd(auxPercpErr(spatial_idx3));
end

% save(storeFile,'train_PE_angle_session','train_PE_angle_subject',...
%          'train_PE_session','train_PE_subject','train_PE_subject_3_spatial_zones');
%      
     
     
     
   
     
     
     
     
     
 %% ----------------- Linear model for extracting auditory width which takes 
 % ------------- into account spatial biases and spatial variation in width

% fig = figure;
% fig.Color = [1 1 1];
train_angles = unique(training_all_outcome);
angle_bin_size = 3;
train_PE_subject_spaceBinned_corrected = [];
train_PE_subject_bias_binned = [];
train_PE_subject_spaceBinned_raw = [];

%subject estimates corrected for bias towards center
training_all_corrected_estimate = nan(length(training_all_outcome),1);

 for i1 = 1:length(unique(ID))
    
    selSubj = training_all_ID == i1;
    auxPercpErr = training_all_percpErr(selSubj);
    auxOutcome = training_all_outcome(selSubj);
    
    subj_mean_err = nan(length(train_angles)-(angle_bin_size-1),1);
    mean_train_angles = nan(length(train_angles)-(angle_bin_size-1),1);
    for i2 = 1:length(train_angles)-(angle_bin_size-1)
       aux_idx = auxOutcome >= train_angles(i2) & ...
                 auxOutcome <= train_angles(i2+(angle_bin_size-1));
       subj_mean_err(i2) = nanmean(auxPercpErr(aux_idx));
       mean_train_angles(i2) = mean(train_angles(i2:i2+(angle_bin_size-1)));
        
    end
%     
%     subplot(5,4,i1);
%     hold on
%     h1 = plot(mean_train_angles,subj_mean_err,'b.-','linewidth',2,'markersize',12);
%     grid on
%     title('Mean error')
    
%     X = [ones(length(mean_train_angles),1)  (90 - mean_train_angles)];
%     Y = subj_mean_err;
%     
%     [b_angle_bias] = robustfit(X,Y,[],[],'off');
    
    [~,aux_angle_idx] = min(abs(bsxfun(@minus,90- training_all_outcome(selSubj),mean_train_angles')),[],2);
    training_all_corrected_estimate(selSubj) = training_all_estimate(selSubj) ...
                                       + subj_mean_err(aux_angle_idx);
    
                                   
    subj_spatial_std_corrected = nan(length(train_angles)-(angle_bin_size-1),1);
    subj_spatial_std_raw = nan(length(train_angles)-(angle_bin_size-1),1);
    aux_corrected_percpErr = auxOutcome - training_all_corrected_estimate(selSubj);
    aux_corrected_percpErr(abs(aux_corrected_percpErr)>40) = nan;
    for i2 = 1:length(train_angles)-(angle_bin_size-1)
       aux_idx = auxOutcome >= train_angles(i2) & ...
                 auxOutcome <= train_angles(i2+(angle_bin_size-1));
       subj_spatial_std_corrected(i2) = nanstd(aux_corrected_percpErr(aux_idx));
       subj_spatial_std_raw(i2) = nanstd(auxPercpErr(aux_idx));
    end
    
    train_PE_subject_spaceBinned_corrected(i1,:) = subj_spatial_std_corrected;
    train_PE_subject_spaceBinned_raw(i1,:) = subj_spatial_std_raw;
    
    train_PE_subject_bias_binned(i1,:) = subj_mean_err;
%   
%     subplot(5,4,i1);
%     hold on
%     h1 = plot(mean_train_angles,subj_spatial_std_corrected,'b.-','linewidth',2,'markersize',12);
%     h2 = plot(mean_train_angles,subj_spatial_std_raw,'r.-','linewidth',2,'markersize',12);
%     ylim([5 25])
%     grid on
                                   
 end
 

 
 save(storeFile,'train_PE_angle_session','train_PE_angle_subject',...
         'train_PE_session','train_PE_subject','train_PE_subject_3_spatial_zones',...
          'train_PE_subject_spaceBinned_corrected','train_PE_subject_spaceBinned_raw',...
          'mean_train_angles','train_angles','train_PE_subject_bias_binned', ...
           'training_all_percpErr','training_all_outcome','training_all_estimate',...
           'training_all_ID');
     