clear
clc
close all

dataDir = fullfile('/Users', 'jigold', 'GoldWorks', 'Mirror_lab', ...
    'Meetings', 'SFN', 'SFN2016', 'Glaze', 'Data');

% MAIN PLOT CODE FOR THE RIGHT PANEL IN THE 2016 SFN POSTER PDF IN THE SAME
% FOLDER. WRITTEN BY CHRIS GLAZE 2016 (cmglaze@gmail.com).
%
%

% The was generated by pupil_analysis.m
load(fullfile(dataDir, 'pupildata.mat'));

% This was generated by indiff_anl.m. Contains adaptability measures. Code
% right now ignores but we can use variables to bin analysis by how much
% people adapted using the cutoff variable (ranges from -2 to 2, ideal is
% 1, is a regression coeffocient of fit H on task H).
load(fullfile(dataDir, 'indiffdata.mat'));
%load(fullfile(dataDir, 'regcoeff1.mat'));
%load(fullfile(dataDir, 'regcoeff2.mat'));
%load(fullfile(dataDir, 'regcoeff3.mat'));

cutoff = 2;

% Tolerance for pupil dropout proportion. 
dropoutcutoff = .2;

pupilmnmn1 = mean(pupilmnnorm1(regcoeff1<cutoff & dropoutvc1<dropoutcutoff,:));
pupilmnmn2 = mean(pupilmnnorm2(regcoeff2<cutoff & dropoutvc2<dropoutcutoff,:));
pupilmnmn3 = mean(pupilmnnorm3(regcoeff3<cutoff & dropoutvc3<dropoutcutoff,:));


% THIS WAS GENERATED BY generate_model_vars.m
load(fullfile(dataDir, 'modelevs.mat'));

Hdelay = 4;

load(fullfile(dataDir, 'stimPilot_auditory_2AFC_080116.mat'));
stimvc3 = stimvc;
Hvc3 = Hvc;
zvc3 = z;
CP3 = [1 double(zvc3(2:end)~=zvc3(1:end-1))];
% CP3 = [1;double(stimvc3(2:end)~=stimvc3(1:end-1))];
R3 = cp2run(CP3);
Hprevc3 = [.5*ones(Hdelay,1);Hvc3(1:end-Hdelay)];
Rprevc3 = [0;R3(1:end-1)];

CP_H_3 = [1;double(Hvc3(2:end)~=Hvc3(1:end-1))];
R_H_3 = cp2run(CP_H_3);
Rprev_H_3 = [zeros(Hdelay,1);R_H_3(1:end-Hdelay)];

load(fullfile(dataDir, 'stimPilot_auditory_2AFC_071816.mat'));
stimvc2 = stimvc;
Hvc2 = Hvc;
zvc2 = z;
CP2 = [1 double(zvc2(2:end)~=zvc2(1:end-1))];
% CP2 = [1;double(stimvc2(2:end)~=stimvc2(1:end-1))];
R2 = cp2run(CP2);
Hprevc2 = [.5*ones(Hdelay,1);Hvc2(1:end-Hdelay)];
Rprevc2 = [0;R2(1:end-1)];

CP_H_2 = [1;double(Hvc2(2:end)~=Hvc2(1:end-1))];
R_H_2 = cp2run(CP_H_2);
Rprev_H_2 = [zeros(Hdelay,1);R_H_2(1:end-Hdelay)];

load(fullfile(dataDir, 'stimPilot_auditory_2AFC_071116.mat'));
stimvc1 = stimvc;
Hvc1 = Hvc;
zvc1 = z;
CP1 = [1 double(zvc1(2:end)~=zvc1(1:end-1))];
% CP1 = [1;double(stimvc1(2:end)~=stimvc1(1:end-1))];
R1 = cp2run(CP1);
Hprevc1 = [.5*ones(Hdelay,1);Hvc1(1:end-Hdelay)];
Rprevc1 = [0;R1(1:end-1)];

CP_H_1 = [1;double(Hvc1(2:end)~=Hvc1(1:end-1))];
R_H_1 = cp2run(CP_H_1);
Rprev_H_1 = [zeros(Hdelay,1);R_H_1(1:end-Hdelay)];


Hall = [Hvc1;Hvc2;Hvc3];
Hprevall = [vec(Hprevc1(2:end));vec(Hprevc2(2:end));vec(Hprevc3(2:end))];
Rall = [vec(R1(2:end));vec(R2(2:end));vec(R3(2:end))];

Rprev_H_all = [vec(Rprev_H_1(2:end));vec(Rprev_H_2(2:end));vec(Rprev_H_3(2:end))];

correctmnall = [vec(correctmn1(2:end));vec(correctmn2(2:end));vec(correctmn3(2:end))];

Rprevall = [vec(Rprevc1(2:end));vec(Rprevc2(2:end));vec(Rprevc3(2:end))];

LP1 = L1 - LLR1;
LP2 = L2 - LLR2;
LP3 = L3 - LLR3;

pupilmnall = [vec(pupilmnmn1(2:end));vec(pupilmnmn2(2:end));vec(pupilmnmn3(2:end))];

Hsampall = [vec(Hsamp1(2:end));vec(Hsamp2(2:end));vec(Hsamp3(2:end))];
Hsamprevall = [vec(Hsamp1(1:end-1));vec(Hsamp2(1:end-1));vec(Hsamp3(1:end-1))];

zvc1 = double(zvc1(:)==2);
zvc2 = double(zvc2(:)==2);
zvc3 = double(zvc3(:)==2);

correct1 = double(LP1(2:end)>0)==zvc1(2:end);
correct2 = double(LP2(2:end)>0)==zvc2(2:end);
correct3 = double(LP3(2:end)>0)==zvc3(2:end);

modcorrectall = [correct1(:);correct2(:);correct3(:)];


% HERE WE ARE DEFINING MODEL SURPRISE

% this is most principled measure based on model evidence
logwall = -1*[vec(logw1(2:end));vec(logw2(2:end));vec(logw3(2:end))];

% this is an alternative based on absolute change
% in expected hazard rate
logwall = abs(Hsampall-Hsamprevall);

Hset = [.01 .3 .99];
Rbins = [1 2 4 6 8 inf];

pupilmat = zeros(numel(Hset),numel(Rbins)-1)+nan;
correctmat = pupilmat;
negevmat = pupilmat;
modcorrectmat = pupilmat;
Nmat = pupilmat;
Hmat = pupilmat;
correctsemat = correctmat;
pupilsemat = correctmat;

% Rbins = [1 2 3 4 5 inf];
xlabs = {'1','2','3','4-5','6-8','9+'};


indsval0 = Rprev_H_all>=100;

for Hind = 1:numel(Hset)
    for Rind = 1:numel(Rbins)-1
        
        indsval = Hprevall==Hset(Hind) & Rall>=Rbins(Rind) & Rall<Rbins(Rind+1) & indsval0;
        if sum(indsval)>2
            pupilmat(Hind,Rind) = mean(pupilmnall(indsval));
            correctmat(Hind,Rind) = mean(correctmnall(indsval));
            negevmat(Hind,Rind) = mean(logwall(indsval));
            modcorrectmat(Hind,Rind) = mean(modcorrectall(indsval));
            Hmat(Hind,Rind) = mean(Hsampall(indsval));
            
            correctsemat(Hind,Rind) = std(bootstrp(500,@mean,correctmnall(indsval)));
            pupilsemat(Hind,Rind) = std(bootstrp(500,@mean,pupilmnall(indsval)));
            
        end
        
        Nmat(Hind,Rind) = sum(indsval);
        
    end
end

linestylearr = {'-','-.','--'};

figure
plot(modcorrectmat','-o','linewidth',2)
legend({'H=0.01','H=0.3','H=0.99'})
set(gca,'box','off','ticklength',[0 0],'fontsize',12,'xtick',[1:numel(Rbins)-1],'xticklabel',xlabs)

ylim([0 1])
xlim([.5 numel(Rbins)-.5])
set(gcf,'Position',[751   620   281   184])
ylabel('Model pr(correct)','fontsize',14)
xlabel('Trials post-changepoint','fontsize',14)

figure
for i = 1:3
    hold on
    errorbar(correctmat(i,:),correctsemat(i,:),'linewidth',2)
end
legend({'H=0.01','H=0.3','H=0.99'})
set(gca,'box','off','ticklength',[0 0],'fontsize',12,'xtick',[1:numel(Rbins)-1],'xticklabel',xlabs)

ylim([0 1])
xlim([.5 numel(Rbins)-.5])
set(gcf,'Position',[751   620   281   184])
ylabel('Pr(correct)','fontsize',14)
xlabel('Trials post-changepoint','fontsize',14)

figure
for i = 1:3
    hold on
    errorbar(pupilmat(i,:),pupilsemat(i,:),'linewidth',2)
end
xlim([.5 numel(Rbins)-.5])
legend({'H=0.01','H=0.3','H=0.99'})
ylabel('Normalized pupil diameter','fontsize',14)
xlabel('Trials post-changepoint','fontsize',14)

set(gca,'box','off','ticklength',[0 0],'fontsize',12,'xtick',[1:numel(Rbins)-1],'xticklabel',xlabs)
set(gcf,'Position',[751   620   281   184])


figure
for i = 1:3
    hold on
    plot(negevmat(i,:),'linewidth',2)
end
xlim([.5 numel(Rbins)-.5])
legend({'H=0.01','H=0.3','H=0.99'})
ylabel('Model surprise','fontsize',14)
xlabel('Trials post-changepoint','fontsize',14)

set(gca,'box','off','ticklength',[0 0],'fontsize',12,'xtick',[1:numel(Rbins)-1],'xticklabel',xlabs)
set(gcf,'Position',[751   620   281   184])

